# .pre-commit-config.yaml
-   repo: https://github.com/sqlfluff/sqlfluff
    rev: v0.14.0
    hooks:
    -   id: sqlfluff
        name: SQLFluff
        files: \.sql$  # Only run on .sql files
        args:
          - --config
          - .sqlfluff  # Path to your SQLFluff config file
