
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'quip_data'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'bigquery'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# Config indicated by + and applies to all files under models/example/
models:
  quip_data: # these configs apply to all layers
    +persists_docs: # This persists our documentiation on BQ UI
      relation: true
      columns: true
    +materialized: table
    stage:
      +database: quip-dw-stage
      +docs:
        node_color: "#900C3F"
      shopify:
        +schema: shopify
      recharge:
        +schema: recharge
    intermediate:
      +database: quip-dw-intermediate
      +docs:
        node_color: "#1577ef"
      users:
        +schema: users
    mart:
      +database: quip-dw-mart
      +schema: mart
      node:color: "#fcba03"

# Configuring seeds
# Full documentation: https://docs.getdbt.com/docs/configuring-seeds
seeds:
  quip_data:
    +database: quip-dw-stage
    +schema: seeds
    +docs:
      node_color: "#f0699d"
    +tags:
      - seed