name: 'quip_data'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'bigquery'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets: # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# Config indicated by + and applies to all files under models/example/
# directories are listed in alphabetical order
models:
  quip_data: # these configs apply to all layers
    +persists_docs: # This persists our documentation on BQ UI
      relation: true
      columns: true
    +materialized: table
    # dbt-osmosis configurations
    +dbt-osmosis: "schemas/{model}.yml" # all files will be created in the schemas directory
    +dbt-osmosis-options:
        skip-add-tags: true
        output-to-lower: true
        force-inherit-descriptions: true
        sort-by: "alphabetical"

    stage:
      +database: quip-dw-stage
      +docs:
        node_color: "#900C3F"
      alloy:
        +schema: alloy
      ceva:
        +schema: ceva
      legacy_segment:
        +schema: legacy_segment
      littledata:
        +schema: littledata
      quip_public:
        +schema: quip_public
      recharge:
        +schema: recharge
      rudderstack:
        +schema: rudderstack
      shopify:
        +schema: shopify
      stord:
        +schema: stord
      tiktok_ads:
        +schema: tiktok_ads
      wen_parker:
        +schema: wen_parker
        +materialized: view # temp materialization as legacy dbt models are dependent on these models

    intermediate:
      +database: quip-dw-intermediate
      +docs:
        node_color: "#1577ef"
      logistics:
        +schema: logistics
      order_items:
        +schema: order_items
      orders:
        +schema: orders
      payments:
        +schema: payments
      products:
        +schema: products
      subscriptions:
        +schema: subscriptions
      users:
        +schema: users
    
    mart:
      +database: quip-dw-mart
      +schema: mart
      node:color: "#fcba03"
      dims:
        +schema: dims
      facts:
        +schema: facts
      finance:
        +schema: finance
      marketing:
        +schema: marketing
      operations:
        +schema: operations
      quip:
        +schema: quip

# Configuring seeds
# Full documentation: https://docs.getdbt.com/docs/configuring-seeds
seeds:
  quip_data:
    +database: quip-dw-stage
    +schema: seeds
    +docs:
      node_color: "#f0699d"
    +tags:
      - seed
